use crate::prelude::*;
use std::env;
use std::path::{Path, PathBuf};

const TARGET_FRAMEWORKS: &[&str] = &["net9.0", "net10.0"];

struct DotnetSolution {
    path: &'static str,
    artifact_project: &'static str,
    set_platform: bool,
}

const SOLUTIONS: &[DotnetSolution] = &[
    DotnetSolution {
        path: "protocols/NowProto.sln",
        artifact_project: "protocols/dotnet/Devolutions.NowProto",
        set_platform: true,
    },
    DotnetSolution {
        path: "policies/dotnet/Devolutions.Now.Policy.slnx",
        artifact_project: "policies/dotnet/Devolutions.Now.Policy.Model",
        set_platform: false,
    },
];

pub fn fmt(sh: &Shell) -> anyhow::Result<()> {
    let _s = Section::new("DOTNET-FORMATTING");

    for solution in SOLUTIONS {
        let solution_path = solution.path;
        let output = cmd!(sh, "dotnet format {solution_path} --verify-no-changes")
            .ignore_status()
            .output()?;

        if !output.status.success() {
            anyhow::bail!("Bad formatting, please run 'dotnet format {solution_path}'");
        }
    }

    println!("All good!");

    Ok(())
}

pub fn get_target_arch() -> anyhow::Result<&'static str> {
    match env::consts::ARCH {
        "x86_64" => Ok("x64"),
        "aarch64" => Ok("ARM64"),
        _ => anyhow::bail!("Unsupported architecture: {}", env::consts::ARCH),
    }
}

fn get_dotnet_output_path(solution: &DotnetSolution, target_framework: &str) -> anyhow::Result<PathBuf> {
    let build_config = "Debug";

    let mut output_path = Path::new(solution.artifact_project).join("bin");

    if solution.set_platform {
        output_path = output_path.join(get_target_arch()?);
    }

    output_path = output_path.join(build_config).join(target_framework);

    Ok(output_path)
}

fn list_files_for_target_framework(
    sh: &Shell,
    solution: &DotnetSolution,
    target_framework: &str,
) -> anyhow::Result<()> {
    let build_path = get_dotnet_output_path(solution, target_framework)?;
    let absolute_build_path = sh.current_dir().join(&build_path);
    if !absolute_build_path.exists() {
        anyhow::bail!("Expected build output directory does not exist: {:?}", build_path);
    }

    list_files(sh, build_path.to_str().unwrap()).context(format!(
        "failed to list artifacts generated by dotnet build ({})",
        target_framework
    ))?;
    Ok(())
}

pub fn build(sh: &Shell) -> anyhow::Result<()> {
    let _s = Section::new("DOTNET-BUILD");

    for solution in SOLUTIONS {
        let solution_path = solution.path;
        if solution.set_platform {
            let platform = get_target_arch()?;
            cmd!(sh, "dotnet build {solution_path} -p:Platform={platform}").run()?;
        } else {
            cmd!(sh, "dotnet build {solution_path}").run()?;
        }

        if is_verbose() {
            for &target_framework in TARGET_FRAMEWORKS {
                list_files_for_target_framework(sh, solution, target_framework)?;
            }
        }
    }

    println!("All good!");

    Ok(())
}

pub fn tests_run(sh: &Shell) -> anyhow::Result<()> {
    let _s = Section::new("DOTNET-TESTS-RUN");

    for solution in SOLUTIONS {
        let solution_path = solution.path;
        if solution.set_platform {
            let platform = get_target_arch()?;
            cmd!(sh, "dotnet test {solution_path} -p:Platform={platform}").run()?;
        } else {
            cmd!(sh, "dotnet test {solution_path}").run()?;
        }
    }

    println!("All good!");

    Ok(())
}
